"use strict";
let age = 25;
const myName = "John";
let isStudent = true;
let numList;
numList = [1, 2, 3, 4, 5, 6];
console.log(numList.filter((num) => num > 4));
age = 25.697451;
console.log(age.toString());
console.log(myName);
